# Generated by Django 3.0.5 on 2021-07-19 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(default='null', upload_to='articulos/', verbose_name='Pic')),
                ('createdo_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('atualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el :')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
