# Generated by Django 3.0.5 on 2021-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_post_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createdo_el'], 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='Ceo', max_length=20, verbose_name='Cargo'),
        ),
    ]
