# Generated by Django 3.0.5 on 2021-07-31 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0003_auto_20210722_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='publicacaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
